### ISSUE TITLE
What's the status ?

### ISSUE THREAD

**Issue by prahaladbelavadi** [beerjs/bangalore#1]
What's the status  of Beerjs meetups in Bangalore ?

If there's already an established community, I'd love to join and help out, If not I'd like to help create one

Thanks

**Comment by jordanpapaleo** [comment]
Let me know if you would like access to work on the group :)

**Comment by prahaladbelavadi** [comment]
Yeah totally,
That'd be great
Thank you @jordanpapaleo

**Comment by jordanpapaleo** [comment]
I created a new team for Bangalore and added you.  This team has write permissions to the repo.  You should start off by updating your README.md file and make sure to join our slack channel :)

Feel free to DM me on twitter if you need anything @jordanpapaleo
